### ISSUE TITLE
Augmentation method is unclear

### ISSUE THREAD

**Issue by cemildemir19** [cageyoko/CTC-Attention-Mispronunciation#1]
I could not find any code how you are doing augmentation. I also read the paper but it seems not clear to me. Could you clarify augmentation strategy?

**Comment by cageyoko** [comment]
Ok.  in utils/data_loader.py 126 line,  we use data augmentation in traning.  the  data augentation function in utils/tools....
three difference augmentation strategy to modifiy input phonme sequence:
first randomly select phoneme in input phonme sequence, suppose the phoneme is A
strategy 1:  randomly select phoneme from all phoneme set(43) to replace A 
strategy 2:  
Firstly we define vowels = ['iy', 'aa', 'ae', 'eh', 'ah', 'ao', 'ih', 'ey', 'aw', 'ay', 'er', 'uw', 'uh', 'oy', 'ow'] 
consonants = ['w', 'dh', 'y', 'hh', 'ch', 'jh', 'th', 'zh', 'd', 'ng', 'b', 'g', 'f', 'k', 'm', 'l', 'n', 's', 'r', 't', 'v', 'z', 'p', 'sh']
later  if A is vowel, randomly select phoneme from all vowel  set to replace A.
         if A is consonant, randomly select phoneme from all consonant  set to replace A.
strategy 3: we count the confusing pairs of mispronunciation in L2-arctic training set part. if A in confusing sets, randomly select phoneme from confusing pairs  to replace A.

Thank you for your interest in this project, maybe the augmentation coding is messy, I try to update it again and add more new function, such as support multi-gpu parallel compute

**Comment by cemildemir19** [comment]
Thank you for your response.
