### ISSUE TITLE
Can't find fbank.scp

### ISSUE THREAD

**Issue by ttb06** [cageyoko/CTC-Attention-Mispronunciation#10]
When running run.sh, I got this problem:

Traceback (most recent call last):
  File "/content/CTC-Attention-Mispronunciation/egs/attention_aug/steps/train_ctc.py", line 278, in <module>
    main(conf)
  File "/content/CTC-Attention-Mispronunciation/egs/attention_aug/steps/train_ctc.py", line 108, in main
    train_dataset = SpeechDataset(vocab, opts.train_scp_path, opts.train_lab_path,opts.train_trans_path, opts, True)
  File "/content/CTC-Attention-Mispronunciation/egs/attention_aug/./utils/data_loader.py", line 77, in __init__
    self.process_feature_label()
  File "/content/CTC-Attention-Mispronunciation/egs/attention_aug/./utils/data_loader.py", line 82, in process_feature_label
    with open(self.scp_path, 'r') as rf:
FileNotFoundError: [Errno 2] No such file or directory: 'data/train/fbank.scp'

Where can I find this file?

**Comment by dyustc** [comment]
I came across the same problem, there is a raw_fbank.scp under the train folder, I guess we have to split it into a fbank.scp under separate folders: train, dev, test, but I haven't try it yet.

**Comment by ttb06** [comment]
Can you show me this? I have checked my folder but I can't find it.

Btw, I think fbank ís created by Kaldi, but I can't run the command which
is related to Kaldi :< Can you run something like "fbank", "
compute-fbank-feats"...?

Thanks.

**Comment by dyustc** [comment]
> Can you show me this? I have checked my folder but I can't find it. Btw, I think fbank ís created by Kaldi, but I can't run the command which is related to Kaldi :< Can you run something like "fbank", " compute-fbank-feats"...? Thanks.

I delete the post cuz I manully changed the code, so it won't produce fbank.scp.  I rollback my change, there would fbank.scp in train, dev, and test. 

So if I have to guess,  you can check if you can successfully run compute-fbank-feats at first, and either the input wav.scp or wav_sph.scp must be in the correct format.

**Comment by cageyoko** [comment]
Hey, sorry for late reply. You should first make sure you have installed kaldi[https://github.com/kaldi-asr/kaldi] correctly, and then follow the instructions (https://github.com/cageyoko/CTC-Attention-Mispronunciation/issues/4) run it step by step.

**Comment by ttb06** [comment]
> Hey, sorry for late reply. You should first make sure you have installed kaldi[https://github.com/kaldi-asr/kaldi] correctly, and then follow the instructions (#4) run it step by step.

I have installed Kaldi, and I think my problem comes from other reason: I saw that the steps file doesn't have the file which make_feat.sh needs (fbank, compute-fbank-feats, ...). And I found that these files are in src folder of Kaldi. So how do you run all of this with this steps folder :<

**Comment by cageyoko** [comment]
> > Hey, sorry for late reply. You should first make sure you have installed kaldi[https://github.com/kaldi-asr/kaldi] correctly, and then follow the instructions (#4) run it step by step.
> 
> I have installed Kaldi, and I think my problem comes from other reason: I saw that the steps file doesn't have the file which make_feat.sh needs (fbank, compute-fbank-feats, ...). And I found that these files are in src folder of Kaldi. So how do you run all of this with this steps folder :<

Check whether the command can work.
if it work, your path setting is wrong. else you haven't installed Kaldi correctly.
<img width="673" alt="image" src="https://github.com/cageyoko/CTC-Attention-Mispronunciation/assets/35170030/c4c4f32f-0b33-4cca-b6ea-869e14e2481c">
