### ISSUE TITLE
Question about Data Augmentation

### ISSUE THREAD

**Issue by huutuongtu** [cageyoko/CTC-Attention-Mispronunciation#12]
Hi. I have a question about your data augmentation strategy.
Did you use data augmentation in training only? Or when infer with test set, you augment canonical phoneme too or keep original canonical phoneme?

**Comment by cageyoko** [comment]
Since it takes too long, if I remember correctly that data augmentation is
used during training and testing, you can try turning it off during testing.

Huu Tuong Tu ***@***.***> 于2023年12月20日周三 12:27写道：
