### ISSUE TITLE
does the code include MD&D evaluation implementation?

### ISSUE THREAD

**Issue by Mu-Y** [cageyoko/CTC-Attention-Mispronunciation#2]
Hello,

Does this code include the MD&D evaluation implementation?, i.e. these shown in table 3 in the paper (True Accept, True rejection, etc.).

Thanks.

**Comment by cageyoko** [comment]
yes,  the MD&D evaluation code  in the ./ egs/attention_aug/result/mdd_result.sh

**Comment by cageyoko** [comment]
True Accept etc will be computed by "egs/attention_aug/result/utils/scoring/ins_del_sub_cor_analysis.py"
