### ISSUE TITLE
Usage difficulties

### ISSUE THREAD

**Issue by bannayeva** [cageyoko/CTC-Attention-Mispronunciation#4]
Hi, i followed the steps in your Usage section, but i'm not sure what to do next. Could you please give more details? How should i train your model?

**Comment by cageyoko** [comment]
1. ensure your kaldi is work

2. In path.sh, you need change the path,  
original :KALDI_ROOT=/home/ljh/kaldi
revise   :KALDI_ROOT=your kaldi path
3. In run.sh , change 
original :l2arctic_dir="/home/ljh/data/L2-Arctic/data" 
original :timit_dir='/home/ljh/data/timit'

revise   : l2arctic_dir = your l2-arctic path
revise   : timit_dir= your timit path 

I think it will be work for you. if you have any question, plz let me know.

**Comment by bannayeva** [comment]
thank you, what should i expect after running run.sh file?

**Comment by bannayeva** [comment]
for me the code exits with 1
