### ISSUE TITLE
Why use separate key/value for the text embedding?

### ISSUE THREAD

**Issue by rbracco** [cageyoko/CTC-Attention-Mispronunciation#5]
Hi, thank you so much for sharing your paper and code, it has been enjoyable to read and experiment with. In the paper/code, the `value` is the output of the BiLSTM and the `key` is the `value` passed through a linear layer.  Was there a specific reason you chose to use a different key and value here? Did you experiment with different combinations? (example: using the output of the linear layer as both key and value, or using output of the BiLSTM as both key and value). Thanks again!

**Comment by cageyoko** [comment]
hi, I do not experiment with different combinations. because I find the impact of the text is huge, I spent more energy on how to reduce this influence to avoid outputting text sequences :)

**Comment by rbracco** [comment]
Thank you, and am I correct in understanding the primary ways you achieved
that were A. concatting the audio to the context vector before the final
linear layer and B. Substituting values in the text label during training
(the confusion pairs substitution stuff)? Are there any others I'm missing?
Any other tips? Thank you again for your help and for sharing code.

**Comment by cageyoko** [comment]
yes, your understanding is correct. But I need to tell you, When I add librispeech 960h into train set, the attention-based mispronunciation detection method performance does not seem to be very good.
I currently think this code is only helpful to understand the end-to-end mispronunciation detection process, and the script for calculating F1 score is useful.
