### ISSUE TITLE
请问有没有尝试过将 RNN 替换成 Multi-attention?

### ISSUE THREAD

**Issue by Jingyilang** [cageyoko/CTC-Attention-Mispronunciation#6]
感谢你们的工作，我有点疑问想请教一下，请问你们尝过用 Multi-attention 替换过 RNN 吗？我试了一下，就是原始的 cnn + rnn + ctc 替换成 cnn + multi-head attention + ctc，PER 有 40%，不知道哪里出了问题，所以想请教你们一下。

**Comment by cageyoko** [comment]
抱歉哈,当时没用过multihead-attention  这一部分工作暂时搁置了, 这种文本使用方法可能并不是一个很好的方式, 在没有好的想法之前暂时不会对这部分工作继续下去。
