### ISSUE TITLE
A question about the data processing

### ISSUE THREAD

**Issue by teinhonglo** [cageyoko/CTC-Attention-Mispronunciation#7]
Hi,

There are some mismatch between your phoneme map and phoneme map in the kaldi.

The different as follow:

https://github.com/kaldi-asr/kaldi/blob/master/egs/timit/s5/conf/phones.60-48-39.map#L4
https://github.com/cageyoko/CTC-Attention-Mispronunciation/blob/master/egs/attention_aug/conf/phones.60-48-39.map#L4

https://github.com/kaldi-asr/kaldi/blob/master/egs/timit/s5/conf/phones.60-48-39.map#L16
https://github.com/cageyoko/CTC-Attention-Mispronunciation/blob/master/egs/attention_aug/conf/phones.60-48-39.map#L16

https://github.com/kaldi-asr/kaldi/blob/master/egs/timit/s5/conf/phones.60-48-39.map#L61
https://github.com/cageyoko/CTC-Attention-Mispronunciation/blob/master/egs/attention_aug/conf/phones.60-48-39.map#L61

Any suggestion?

--2022/5/22--
Oh, I got it.
The reason for this is the phoneme table that is used in l2-arctic.
Is that correct?

**Comment by cageyoko** [comment]
I‘m so sorry for my delays in replying to your question.  Yes,  some phonemes do not appear in L2-arctic in the original version. We replace them.
